version: '3.8'

services:
  safemesh-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safemesh-ai-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=safemesh_ai_production_jwt_secret_key_2026
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
    volumes:
      - sqlite_data:/app/backend/prisma
    restart: unless-stopped

volumes:
  sqlite_data:
